// The shared base item every component installs. Listed by explicit files.
export const baseItem = {
    name: 'base',
    type: 'base',
    files: [
        'resources/js/common/helpers/cn.ts',
        'resources/js/common/components/Icon.vue',
    ],
    // tokens.css and the slim icon map are generated by the build.
}

// Component items. `entry` is the file whose import graph defines the item.
// Phase 1 pilot is the five single-file atoms. Composite/foldered families
// (Select, Dialog, Tooltip, Table, Card) are deferred to Phase 1.5, which adds
// folder-based item resolution (their sub-components are auto-registered
// siblings, not imported by the root, so the import graph does not capture them).
export const componentItems = [
    { name: 'button', type: 'component', entry: 'resources/js/common/components/ui/Button.vue' },
    { name: 'badge', type: 'component', entry: 'resources/js/common/components/ui/Badge.vue' },
    { name: 'label', type: 'component', entry: 'resources/js/common/components/ui/Label.vue' },
    { name: 'separator', type: 'component', entry: 'resources/js/common/components/ui/Separator.vue' },
    { name: 'input', type: 'component', entry: 'resources/js/common/components/ui/Input.vue' },
    { name: 'breadcrumbs', type: 'component', entry: 'resources/js/common/components/ui/Breadcrumbs.vue' },
    { name: 'skeleton', type: 'component', entry: 'resources/js/common/components/ui/Skeleton.vue' },
    { name: 'textarea', type: 'component', entry: 'resources/js/common/components/ui/Textarea.vue' },
    { name: 'toggle', type: 'component', entry: 'resources/js/common/components/ui/Toggle.vue' },
    { name: 'kbd', type: 'component', entry: 'resources/js/common/components/ui/Kbd.vue' },
    { name: 'kbdgroup', type: 'component', entry: 'resources/js/common/components/ui/KbdGroup.vue' },
    { name: 'chip', type: 'component', entry: 'resources/js/common/components/ui/Chip.vue' },
    { name: 'heading', type: 'component', entry: 'resources/js/common/components/ui/Heading.vue' },
    { name: 'divider', type: 'component', entry: 'resources/js/common/components/ui/Divider.vue' },
    { name: 'rating', type: 'component', entry: 'resources/js/common/components/ui/Rating.vue' },
    { name: 'container', type: 'component', entry: 'resources/js/common/components/ui/Container.vue' },
    { name: 'aspectratio', type: 'component', entry: 'resources/js/common/components/ui/AspectRatio.vue' },
    { name: 'statblock', type: 'component', entry: 'resources/js/common/components/ui/StatBlock.vue', registryDependencies: ['badge'] },
    { name: 'loader', type: 'component', entry: 'resources/js/common/components/ui/Loader.vue' },
    { name: 'placeholder', type: 'component', entry: 'resources/js/common/components/ui/Placeholder.vue' },
    { name: 'nativeselect', type: 'component', entry: 'resources/js/common/components/ui/NativeSelect.vue' },
    { name: 'formselect', type: 'component', entry: 'resources/js/common/components/ui/FormSelect.vue', registryDependencies: ['label', 'form'] },
    { name: 'currencyinput', type: 'component', entry: 'resources/js/common/components/ui/CurrencyInput.vue' },
    { name: 'decimalinput', type: 'component', entry: 'resources/js/common/components/ui/DecimalInput.vue', registryDependencies: ['input'] },
    { name: 'numberinput', type: 'component', entry: 'resources/js/common/components/ui/NumberInput.vue' },
    { name: 'inputcontrol', type: 'component', entry: 'resources/js/common/components/ui/InputControl.vue' },
    { name: 'datefield', type: 'component', entry: 'resources/js/common/components/ui/DateField.vue' },
    { name: 'dateinput', type: 'component', entry: 'resources/js/common/components/ui/DateInput.vue' },
    { name: 'datepicker', type: 'component', entry: 'resources/js/common/components/ui/Datepicker.vue' },
    { name: 'vee-input', type: 'component', entry: 'resources/js/common/components/ui/Vee/Input.vue', registryDependencies: ['label'] },
    { name: 'vee-textarea', type: 'component', entry: 'resources/js/common/components/ui/Vee/Textarea.vue', registryDependencies: ['label'] },
    { name: 'vee-checkbox', type: 'component', entry: 'resources/js/common/components/ui/Vee/Checkbox.vue' },
    { name: 'vee-select', type: 'component', entry: 'resources/js/common/components/ui/Vee/Select.vue', registryDependencies: ['label'] },
    { name: 'vee-radiogroup', type: 'component', entry: 'resources/js/common/components/ui/Vee/RadioGroup.vue', registryDependencies: ['label'] },
    { name: 'vee-multiselect', type: 'component', entry: 'resources/js/common/components/ui/Vee/MultiSelect.vue', registryDependencies: ['label'] },
    { name: 'vee-tagsinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/TagsInput.vue', registryDependencies: ['label'] },
    { name: 'vee-numberfield', type: 'component', entry: 'resources/js/common/components/ui/Vee/NumberField.vue', registryDependencies: ['label'] },
    { name: 'vee-vueformslider', type: 'component', entry: 'resources/js/common/components/ui/Vee/VueFormSlider.vue', registryDependencies: ['label'] },
    { name: 'vee-inputpin', type: 'component', entry: 'resources/js/common/components/ui/Vee/InputPin.vue', registryDependencies: ['label'] },
    { name: 'vee-currencyinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/CurrencyInput.vue', registryDependencies: ['label'] },
    { name: 'vee-moneyinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/MoneyInput.vue', registryDependencies: ['label'] },
    { name: 'vee-numberinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/NumberInput.vue', registryDependencies: ['label'] },
    { name: 'vee-datefield', type: 'component', entry: 'resources/js/common/components/ui/Vee/DateField.vue', registryDependencies: ['label'] },
    { name: 'vee-dateinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/DateInput.vue', registryDependencies: ['label'] },
    { name: 'vee-datepicker', type: 'component', entry: 'resources/js/common/components/ui/Vee/Datepicker.vue', registryDependencies: ['label'] },
    { name: 'vee-datetimepicker', type: 'component', entry: 'resources/js/common/components/ui/Vee/DateTimePicker.vue', registryDependencies: ['label'] },
    { name: 'vee-calendarpicker', type: 'component', entry: 'resources/js/common/components/ui/Vee/CalendarPicker.vue', registryDependencies: ['label'] },
    { name: 'vee-phoneinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/PhoneInput.vue', registryDependencies: ['label'] },
    { name: 'vee-fileinput', type: 'component', entry: 'resources/js/common/components/ui/Vee/FileInput.vue', registryDependencies: ['label'] },
    { name: 'fullcalendar', type: 'component', entry: 'resources/js/common/components/ui/FullCalendar.vue' },
    { name: 'pdfviewer', type: 'component', entry: 'resources/js/common/components/ui/PdfViewer.vue', registryDependencies: ['button'] },
    { name: 'addressmap', type: 'component', entry: 'resources/js/common/components/ui/AddressMap.vue' },
    { name: 'addressautocomplete', type: 'component', entry: 'resources/js/common/components/ui/AddressAutocomplete.vue', registryDependencies: ['inputcontrol', 'loader'] },
    { name: 'signaturepad', type: 'component', entry: 'resources/js/common/components/ui/SignaturePad.vue', registryDependencies: ['button'] },
    { name: 'imagelightbox', type: 'component', entry: 'resources/js/common/components/ui/ImageLightbox.vue' },
    { name: 'dropfile', type: 'component', entry: 'resources/js/common/components/ui/Dropfile.vue' },
    { name: 'minisparkline', type: 'component', entry: 'resources/js/common/components/ui/MiniSparkline.vue' },
    { name: 'dateperiodselector', type: 'component', entry: 'resources/js/common/components/ui/DatePeriodSelector.vue' },
    { name: 'datetimetooltip', type: 'component', entry: 'resources/js/common/components/ui/DateTimeTooltip.vue', registryDependencies: ['tooltip'] },
    { name: 'licenseplate', type: 'component', entry: 'resources/js/common/components/ui/LicensePlate.vue' },
    { name: 'vee-htmleditor', type: 'component', entry: 'resources/js/common/components/ui/Vee/HtmlEditor.vue', registryDependencies: ['label'] },
    { name: 'vee-markdowneditor', type: 'component', entry: 'resources/js/common/components/ui/Vee/MarkdownEditor.vue', registryDependencies: ['label'] },
    { name: 'borderbeam', type: 'component', entry: 'resources/js/common/components/ui/BorderBeam.vue' },
    { name: 'meteors', type: 'component', entry: 'resources/js/common/components/ui/Meteors.client.vue' },
    { name: 'neongradientcard', type: 'component', entry: 'resources/js/common/components/ui/NeonGradientCard.vue' },
    { name: 'retrogrid', type: 'component', entry: 'resources/js/common/components/ui/RetroGrid.vue' },
    { name: 'gradientdivider', type: 'component', entry: 'resources/js/common/components/ui/GradientDivider.vue' },
    { name: 'fancyicon', type: 'component', entry: 'resources/js/common/components/ui/FancyIcon.vue' },
    { name: 'clientonly', type: 'component', entry: 'resources/js/common/components/ui/ClientOnly.vue' },
    { name: 'iframelazy', type: 'component', entry: 'resources/js/common/components/ui/IframeLazy.vue' },
    { name: 'scrollspy', type: 'component', entry: 'resources/js/common/components/ui/Scrollspy.vue' },
    { name: 'sonner', type: 'component', entry: 'resources/js/common/components/ui/Sonner.vue' },
    { name: 'navbar', type: 'component', entry: 'resources/js/common/components/ui/Navbar.vue' },
    { name: 'imagewithplaceholder', type: 'component', entry: 'resources/js/common/components/ui/ImageWithPlaceholder.vue' },
    // sharebutton deferred: app-coupled (creates backend short URLs + app toast); not a reusable registry primitive.
]

// Composite/foldered families. Each becomes one registry item containing every
// .vue in the folder (auto-registered sub-components) plus inlined family-local files.
export const folderItems = [
    { name: 'select', type: 'component', folder: 'resources/js/common/components/ui/Select' },
    // Dialog's close button uses <Button> in the template (auto-registered, not a
    // script import), so declare the cross-item dependency on `button` explicitly.
    { name: 'dialog', type: 'component', folder: 'resources/js/common/components/ui/Dialog', registryDependencies: ['button'] },
    { name: 'tooltip', type: 'component', folder: 'resources/js/common/components/ui/Tooltip' },
    { name: 'table', type: 'component', folder: 'resources/js/common/components/ui/Table' },
    { name: 'card', type: 'component', folder: 'resources/js/common/components/ui/Card' },
    { name: 'checkbox', type: 'component', folder: 'resources/js/common/components/ui/Checkbox' },
    { name: 'frame', type: 'component', folder: 'resources/js/common/components/ui/Frame' },
    { name: 'dropdownmenu', type: 'component', folder: 'resources/js/common/components/ui/DropdownMenu' },
    { name: 'popover', type: 'component', folder: 'resources/js/common/components/ui/Popover' },
    { name: 'sheet', type: 'component', folder: 'resources/js/common/components/ui/Sheet' },
    { name: 'drawer', type: 'component', folder: 'resources/js/common/components/ui/Drawer' },
    // AlertDialog uses <Button> in its template (auto-registered, not a script import).
    { name: 'alertdialog', type: 'component', folder: 'resources/js/common/components/ui/AlertDialog', registryDependencies: ['button'] },
    { name: 'avatar', type: 'component', folder: 'resources/js/common/components/ui/Avatar' },
    { name: 'alert', type: 'component', folder: 'resources/js/common/components/ui/Alert' },
    { name: 'switch', type: 'component', folder: 'resources/js/common/components/ui/Switch' },
    { name: 'progress', type: 'component', folder: 'resources/js/common/components/ui/Progress' },
    { name: 'radiogroup', type: 'component', folder: 'resources/js/common/components/ui/RadioGroup' },
    { name: 'accordion', type: 'component', folder: 'resources/js/common/components/ui/Accordion' },
    { name: 'tabs', type: 'component', folder: 'resources/js/common/components/ui/Tabs' },
    { name: 'empty', type: 'component', folder: 'resources/js/common/components/ui/Empty' },
    // Pagination uses <Button> in its template.
    { name: 'pagination', type: 'component', folder: 'resources/js/common/components/ui/Pagination', registryDependencies: ['button'] },
    { name: 'command', type: 'component', folder: 'resources/js/common/components/ui/Command', registryDependencies: ['separator'] },
    { name: 'contextmenu', type: 'component', folder: 'resources/js/common/components/ui/ContextMenu' },
    { name: 'navigationmenu', type: 'component', folder: 'resources/js/common/components/ui/NavigationMenu' },
    { name: 'scrollarea', type: 'component', folder: 'resources/js/common/components/ui/ScrollArea' },
    { name: 'collapsible', type: 'component', folder: 'resources/js/common/components/ui/Collapsible' },
    { name: 'stepper', type: 'component', folder: 'resources/js/common/components/ui/Stepper' },
    { name: 'tree', type: 'component', folder: 'resources/js/common/components/ui/Tree' },
    { name: 'treenode', type: 'component', folder: 'resources/js/common/components/ui/TreeNode' },
    { name: 'nav', type: 'component', folder: 'resources/js/common/components/ui/Nav', registryDependencies: ['button', 'separator'] },
    { name: 'sidebar', type: 'component', folder: 'resources/js/common/components/ui/Sidebar', registryDependencies: ['button', 'input', 'separator'] },
    { name: 'list', type: 'component', folder: 'resources/js/common/components/ui/List' },
    { name: 'cardlist', type: 'component', folder: 'resources/js/common/components/ui/CardList' },
    { name: 'timeline', type: 'component', folder: 'resources/js/common/components/ui/Timeline' },
    { name: 'descriptionlist', type: 'component', folder: 'resources/js/common/components/ui/DescriptionList' },
    { name: 'group', type: 'component', folder: 'resources/js/common/components/ui/Group' },
    { name: 'detailview', type: 'component', folder: 'resources/js/common/components/ui/DetailView' },
    { name: 'combobox', type: 'component', folder: 'resources/js/common/components/ui/Combobox' },
    { name: 'listbox', type: 'component', folder: 'resources/js/common/components/ui/Listbox' },
    { name: 'tagsinput', type: 'component', folder: 'resources/js/common/components/ui/TagsInput' },
    { name: 'numberfield', type: 'component', folder: 'resources/js/common/components/ui/NumberField' },
    { name: 'slider', type: 'component', folder: 'resources/js/common/components/ui/Slider', registryDependencies: ['tooltip'] },
    { name: 'inputgroup', type: 'component', folder: 'resources/js/common/components/ui/InputGroup' },
    { name: 'fieldset', type: 'component', folder: 'resources/js/common/components/ui/Fieldset' },
    { name: 'editable', type: 'component', folder: 'resources/js/common/components/ui/Editable' },
    { name: 'form', type: 'component', folder: 'resources/js/common/components/ui/Form', registryDependencies: ['label'] },
    { name: 'inputpin', type: 'component', folder: 'resources/js/common/components/ui/InputPin' },
    { name: 'chart', type: 'component', folder: 'resources/js/common/components/ui/Chart' },
    // DataTable composes Table/Button/Select/DropdownMenu/Checkbox/VeeInput in its
    // templates (auto-registered tags, not script imports), so declare those cross-item
    // dependencies explicitly.
    { name: 'datatable', type: 'component', folder: 'resources/js/common/components/ui/DataTable', registryDependencies: ['button', 'checkbox', 'dropdownmenu', 'select', 'table', 'vee-input'] },
    // CodeBlock's copy button uses <Button> in its template (auto-registered, not a script import).
    { name: 'codeblock', type: 'component', folder: 'resources/js/common/components/ui/CodeBlock', registryDependencies: ['button'] },
]

// Files owned by the base item. Imports resolving here become a `base` registryDependency.
export const baseOwnedPaths = new Set([
    'resources/js/common/helpers/cn.ts',
    'resources/js/common/components/Icon.vue',
])

